// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhRoyHmDVJ0NFum5zeZmNlDJSn5PARXg',
    appId: '1:1096659545399:web:c91cb596edd41229787eb2',
    messagingSenderId: '1096659545399',
    projectId: 'testtools-547f2',
    authDomain: 'testtools-547f2.firebaseapp.com',
    storageBucket: 'testtools-547f2.appspot.com',
    measurementId: 'G-MP0SPN48CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALiPS6F1pC-tz4nzlI_AauU1nDLTsB8tM',
    appId: '1:1096659545399:android:03f5fdc5151d5959787eb2',
    messagingSenderId: '1096659545399',
    projectId: 'testtools-547f2',
    storageBucket: 'testtools-547f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLe6VkQCcMR_qDZZ_ZKwPV_ykvf9Pa3zc',
    appId: '1:1096659545399:ios:b5e8179a0a2e9c41787eb2',
    messagingSenderId: '1096659545399',
    projectId: 'testtools-547f2',
    storageBucket: 'testtools-547f2.appspot.com',
    iosClientId: '1096659545399-g0imtq4prbu40sh6vrc695puplpg47s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLe6VkQCcMR_qDZZ_ZKwPV_ykvf9Pa3zc',
    appId: '1:1096659545399:ios:b5e8179a0a2e9c41787eb2',
    messagingSenderId: '1096659545399',
    projectId: 'testtools-547f2',
    storageBucket: 'testtools-547f2.appspot.com',
    iosClientId: '1096659545399-g0imtq4prbu40sh6vrc695puplpg47s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxSample',
  );
}
